mark fmt::formatter<..>::format() const
mark all `fmt::formatter<..>::format()` with const specifier.

otherwise the tree does not build with fmt 11, like:

```
/usr/include/fmt/base.h: In instantiation of ‘static void fmt::v11::detail::value<Context>::format_custom_arg(void*, typename Context::parse_context_type&, Context&) [with T = crispy::native_handle<int, -1>; Formatter = fmt::v11::formatter<crispy::native_handle<int, -1> >; Context = fmt::v11::context; typename Context::parse_context_type = fmt::v11::basic_format_parse_context<char>]’:
/usr/include/fmt/base.h:1373:19:   required from ‘constexpr fmt::v11::detail::value<Context>::value(T&) [with T = const crispy::native_handle<int, -1>; Context = fmt::v11::context]’
 1373 |     custom.format = format_custom_arg<
      |     ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
 1374 |         value_type, typename Context::template formatter_type<value_type>>;
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/base.h:1631:41:   required from ‘constexpr fmt::v11::detail::format_arg_store<Context, NUM_ARGS, 0, DESC> fmt::v11::make_format_args(T& ...) [with Context = context; T = {const crispy::native_handle<int, -1>}; long unsigned int NUM_ARGS = 1; long unsigned int NUM_NAMED_ARGS = 0; long long unsigned int DESC = 15; typename std::enable_if<(NUM_NAMED_ARGS == 0), int>::type <anonymous> = 0]’
 1631 |   return {arg_mapper<Context>().map(val)};
      |                                         ^
/builddir/build/BUILD/contour-terminal-0.4.3.6442-build/contour-0.4.3.6442/src/crispy/logstore.h:111:59:   required from ‘logstore::message_builder& logstore::message_builder::operator()(std::string_view, const Ts& ...) [with Ts = {crispy::native_handle<int, -1>}; std::string_view = std::basic_string_view<char>]’
  111 |         _buffer += fmt::vformat(fmt, fmt::make_format_args(args...));
      |                                      ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/builddir/build/BUILD/contour-terminal-0.4.3.6442-build/contour-0.4.3.6442/src/vtpty/UnixPty.cpp:215:13:   required from here
  215 |     ptyLog()("PTY destroying master (file descriptor {}).", _masterFd);
      |     ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/fmt/base.h:1392:29: error: passing ‘const fmt::v11::formatter<crispy::native_handle<int, -1> >’ as ‘this’ argument discards qualifiers [-fpermissive]
 1392 |     ctx.advance_to(cf.format(*static_cast<qualified_type*>(arg), ctx));
      |                    ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /builddir/build/BUILD/contour-terminal-0.4.3.6442-build/contour-0.4.3.6442/src/vtpty/UnixPty.h:8:
```

Signed-off-by: Kefu Chai <tchaikov@gmail.com>